//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientTest.LabelEditorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LabelEditorServices.ILabelEditorService")]
    public interface ILabelEditorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelEditorService/CreateNewLabel", ReplyAction="http://tempuri.org/ILabelEditorService/CreateNewLabelResponse")]
        string CreateNewLabel(string newLabelText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILabelEditorServiceChannel : WcfClientTest.LabelEditorServices.ILabelEditorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabelEditorServiceClient : System.ServiceModel.ClientBase<WcfClientTest.LabelEditorServices.ILabelEditorService>, WcfClientTest.LabelEditorServices.ILabelEditorService {
        
        public LabelEditorServiceClient() {
        }
        
        public LabelEditorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabelEditorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelEditorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelEditorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateNewLabel(string newLabelText) {
            return base.Channel.CreateNewLabel(newLabelText);
        }
    }
}
