//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVA_LabelEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVA_LabelEditor.Properties.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the selected label &quot;{0}&quot; be deleted?.
        /// </summary>
        public static string DeleteLabelConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteLabelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete label.
        /// </summary>
        public static string DeleteLabelConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteLabelConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was modified. It can&apos;t be saved.
        /// </summary>
        public static string FileChangedCantSaveMessage {
            get {
                return ResourceManager.GetString("FileChangedCantSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File modified.
        /// </summary>
        public static string FileChangedCantSaveTitle {
            get {
                return ResourceManager.GetString("FileChangedCantSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been modified by another program. Do you want to reload it?.
        /// </summary>
        public static string FileChangedReloadMessage {
            get {
                return ResourceManager.GetString("FileChangedReloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File modified.
        /// </summary>
        public static string FileChangedReloadTitle {
            get {
                return ResourceManager.GetString("FileChangedReloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Files.
        /// </summary>
        public static string FileIds {
            get {
                return ResourceManager.GetString("FileIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label selected.
        /// </summary>
        public static string NoLabelSelectedMessage {
            get {
                return ResourceManager.GetString("NoLabelSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label.
        /// </summary>
        public static string NoLabelSelectedTitle {
            get {
                return ResourceManager.GetString("NoLabelSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels were modified. Do you want to save changes?.
        /// </summary>
        public static string SaveFileConfirmMessage {
            get {
                return ResourceManager.GetString("SaveFileConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveFileConfirmTitle {
            get {
                return ResourceManager.GetString("SaveFileConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text may not be empty.
        /// </summary>
        public static string Validate_Add_EmptyText_Message {
            get {
                return ResourceManager.GetString("Validate_Add_EmptyText_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty text.
        /// </summary>
        public static string Validate_Add_EmptyText_Title {
            get {
                return ResourceManager.GetString("Validate_Add_EmptyText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file name selected.
        /// </summary>
        public static string Validate_Add_NoFileId_Message {
            get {
                return ResourceManager.GetString("Validate_Add_NoFileId_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name.
        /// </summary>
        public static string Validate_Add_NoFileId_Title {
            get {
                return ResourceManager.GetString("Validate_Add_NoFileId_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id may not be empty.
        /// </summary>
        public static string Validate_Id_Empty_Message {
            get {
                return ResourceManager.GetString("Validate_Id_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Id.
        /// </summary>
        public static string Validate_Id_Empty_Title {
            get {
                return ResourceManager.GetString("Validate_Id_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id already exists.
        /// </summary>
        public static string Validate_Id_Exists_Message {
            get {
                return ResourceManager.GetString("Validate_Id_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id found.
        /// </summary>
        public static string Validate_Id_Exists_Title {
            get {
                return ResourceManager.GetString("Validate_Id_Exists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id contains the invalid character &quot;=&quot;.
        /// </summary>
        public static string Validate_Id_InvalidCharacter_Message {
            get {
                return ResourceManager.GetString("Validate_Id_InvalidCharacter_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character.
        /// </summary>
        public static string Validate_Id_InvalidCharacter_Title {
            get {
                return ResourceManager.GetString("Validate_Id_InvalidCharacter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model was locked by Microsoft. To add a Label please create an extension model..
        /// </summary>
        public static string Validate_Reload_Locked_Message {
            get {
                return ResourceManager.GetString("Validate_Reload_Locked_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model locked.
        /// </summary>
        public static string Validate_Reload_Locked_Title {
            get {
                return ResourceManager.GetString("Validate_Reload_Locked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New id may not be the same as the old one.
        /// </summary>
        public static string Validate_Rename_OldEqualsNew_Message {
            get {
                return ResourceManager.GetString("Validate_Rename_OldEqualsNew_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Id.
        /// </summary>
        public static string Validate_Rename_OldEqualsNew_Title {
            get {
                return ResourceManager.GetString("Validate_Rename_OldEqualsNew_Title", resourceCulture);
            }
        }
    }
}
